# Download test data artifacts

steps:

# - task: DownloadPipelineArtifact@2
#   inputs:
#     source: 'specific'
#     project: '$(System.TeamProjectId)'
#     pipeline: 4
#     artifact: 'chem_data'
#     path: $(Pipeline.Workspace)/modules/chem_data
#   displayName: Download chem_data

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: '$(System.TeamProjectId)'
    pipeline: 4
    artifact: 'phenix_regression'
    path: $(Pipeline.Workspace)/modules/phenix_regression
  displayName: Download phenix_regression

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: '$(System.TeamProjectId)'
    pipeline: 4
    artifact: 'phenix_examples'
    path: $(Pipeline.Workspace)/modules/phenix_examples
  displayName: Download phenix_examples
